services:
  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:14.5'
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
      - ./sql/setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql

  #  start mailhog
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    restart: always
