export const BLANK_GRID = [
  [
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
  ],
  [
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
  ],
  [
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
  ],
  [
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
  ],
  [
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
  ],
  [
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
  ],
  [
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
  ],
  [
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
  ],
  [
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
  ],
  [
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
    { pos: { x: 0, y: 0 }, piece: null },
  ],
];
